language: python

env:
  global:
  - SDL_VIDEODRIVER=dummy
  - SDL_AUDIODRIVER=dummy
  - SDL_RENDER_DRIVER=software

matrix:
  fast_finish:
  include:
    - os: linux
      python: 2.7
      sudo: required
      env: PYSDL2_DLL_VERSION=2.0.12

    - os: linux
      python: 3.5
      sudo: required
      env: PYSDL2_DLL_VERSION=2.0.12

    - os: linux
      python: 3.6
      sudo: required
      env: PYSDL2_DLL_VERSION=2.0.12

    - os: linux
      python: 3.7
      sudo: required
      env: PYSDL2_DLL_VERSION=2.0.12

    - os: linux
      python: 3.8
      sudo: required
      env: PYSDL2_DLL_VERSION=2.0.12

    - os: linux
      python: pypy
      sudo: required
      env: PYSDL2_DLL_VERSION=2.0.12

    - os: linux
      python: pypy3
      sudo: required
      env: PYSDL2_DLL_VERSION=2.0.12

    - os: linux
      arch: arm64
      python: 3.8
      sudo: required
      env: PYSDL2_DLL_VERSION=2.0.12
      before_install:
        - echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports xenial main universe multiverse restricted" | sudo tee -a /etc/apt/sources.list
        - echo "deb-src http://archive.ubuntu.com/ubuntu xenial main universe multiverse restricted" | sudo tee -a /etc/apt/sources.list
        - sudo dpkg --add-architecture arm64
        - sudo apt-get -qq update
        - sudo apt-get build-dep libsdl2 libsdl2-mixer libsdl2-ttf libsdl2-image libsdl2-gfx
        - sudo apt-get install libmpg123-dev libopus-dev pulseaudio

    - os: linux
      arch: ppc64le
      python: 3.8
      sudo: required
      env: PYSDL2_DLL_VERSION=2.0.12
      before_install:
        - echo "deb [arch=ppc64le] http://ports.ubuntu.com/ubuntu-ports xenial main universe multiverse restricted" | sudo tee -a /etc/apt/sources.list
        - echo "deb-src http://archive.ubuntu.com/ubuntu xenial main universe multiverse restricted" | sudo tee -a /etc/apt/sources.list
        - sudo dpkg --add-architecture ppc64le
        - sudo apt-get -qq update
        - sudo apt-get build-dep libsdl2 libsdl2-mixer libsdl2-ttf libsdl2-image libsdl2-gfx
        - sudo apt-get install libmpg123-dev libopus-dev pulseaudio

    - name: "Python 3.7 on macOS w/ latest SDL2"
      os: osx
      language: shell
      env: PYSDL2_DLL_VERSION=2.0.12
      before_install: export PATH="/usr/local/opt/python/libexec/bin:/usr/local/bin:$PATH"

    - name: "Python 2.7 on macOS w/ latest SDL2"
      os: osx
      language: shell
      env: PYSDL2_DLL_VERSION=2.0.12
      before_install: brew link python@2

    - name: "Python 3.7 on macOS w/ SDL2 2.0.10"
      os: osx
      language: shell
      env: PYSDL2_DLL_VERSION=2.0.10
      before_install: export PATH="/usr/local/opt/python/libexec/bin:/usr/local/bin:$PATH"

    - name: "Python 3.7 on macOS w/ SDL2 2.0.7"
      os: osx
      language: shell
      env: PYSDL2_DLL_VERSION=2.0.7
      before_install: export PATH="/usr/local/opt/python/libexec/bin:/usr/local/bin:$PATH"

    - name: "Python 3.7 on macOS w/ latest Homebrew SDL2"
      os: osx
      language: shell
      before_install: 
        - export PATH="/usr/local/opt/python/libexec/bin:/usr/local/bin:$PATH" # sets Python to 3.x
        - brew install sdl2 sdl2_mixer sdl2_ttf sdl2_image sdl2_gfx

  allow_failures:
    - arch: arm64
    - arch: ppc64le
    - python: pypy
    - python: pypy3
    - name: "Python 3.7 on macOS w/ latest Homebrew SDL2"


before_install:
  # Install SDL2 build dependencies on Linux (overridden on macOS)
  - sudo apt-get -qq update
  - sudo apt-get build-dep libsdl2 libsdl2-mixer libsdl2-ttf libsdl2-image libsdl2-gfx
  - sudo apt-get install libmpg123-dev libopus-dev pulseaudio
  - dbus-launch pulseaudio --start
  - export SDL_AUDIODRIVER=pulse # Try using pulseaudio driver for Linux CI

cache:
  # Avoids re-compiling SDL2 libraries on Linux every build
  directories:
    - dlls 
    - $HOME/.cache/pip # Avoids recompiling numpy every time on PyPy

install:
  - python -m pip install --upgrade pip
  - if [[ -z "$(ls -A dlls)" ]]; then python .ci/getsdl2.py; fi
  - export PYSDL2_DLL_PATH=$(pwd)/dlls
  - python -m pip install --upgrade numpy pytest
  - python -m pip install .

script:
  - python -B -m pytest -vvl -rxXP
