language: python

matrix:
  fast_finish: true
  include:
    - os: linux
      sudo: required
      python: 2.7
    - os: linux
      sudo: required
      python: 3.4
    - os: linux
      sudo: required
      python: 3.5
    - os: linux
      sudo: required
      python: 3.6
    - os: linux
      sudo: required
      python: pypy
    - os: linux
      sudo: required
      python: pypy3
    - os: osx
      language: generic
      env: PYVER=3
    - os: osx
      language: generic
      env: PYVER=2
  allow_failures:
    - os: linux
      sudo: required
      python: pypy
    - os: linux
      sudo: required
      python: pypy3
    - os: osx
      language: generic
      env: PYVER=3
    - os: osx
      language: generic
      env: PYVER=2

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh .ci/install-linux-deps.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh .ci/install-osx-deps.sh; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh .ci/venv-osx.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source pysdl2-venv/bin/activate; fi
  - pip install -U pip
  - pip install -U numpy
  - pip install .

env:
  global:
  - SDL_VIDEODRIVER=dummy
  - SDL_AUDIODRIVER=dummy
  - SDL_RENDER_DRIVER=software

script:
  - python -B -m sdl2.test.util.runtests -v
